user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
#pid        /var/run/nginx.pid;
pid         /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    # https://jellyfin.org/docs/general/networking/nginx/#censor-sensitive-information-in-logs
    log_format stripsecrets '$remote_addr $host - $remote_user [$time_local] '
                            '"$secretfilter" $status $body_bytes_sent '
                            '$request_length $request_time $upstream_response_time $upstream_cache_status '
                            '"$http_referer" "$http_user_agent"';

    map $request $secretfilter {
        ~*^(?<prefix1>.*[\?&]api_key=)([^&]*)(?<suffix1>.*)$   "${prefix1}***$suffix1";
        ~*^(?<prefix1>.*[\?&]ApiKey=)([^&]*)(?<suffix1>.*)$    "${prefix1}***$suffix1";
        default                                                $request;
    }

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    # auth_basic "Restricted";
    # auth_basic_user_file  /etc/nginx/.htpasswd;

    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    # gzip settings
    gzip on;
    gzip_disable "msie6";

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_min_length 256;
    gzip_types
      application/atom+xml
      application/geo+json
      application/javascript
      application/x-javascript
      application/json
      application/ld+json
      application/manifest+json
      application/rdf+xml
      application/rss+xml
      application/xhtml+xml
      application/xml
      font/eot
      font/otf
      font/ttf
      image/svg+xml
      text/css
      text/javascript
      text/plain
      text/xml;

    include /etc/nginx/conf.d/*.conf;
}
