version: 2
updates:
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "America/Toronto"
    labels:
      - dependencies
      - pre-commit
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: "America/Toronto"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: "America/Toronto"
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
