---
ENABLE_LINTERS:
  - SPELL_LYCHEE

FILTER_REGEX_INCLUDE: (^README\.md$|^LICENSE\.md$|^docs/.*\.md$|^\.github/(ISSUE_TEMPLATE/.*\.md|PULL_REQUEST_TEMPLATE\.md)$)
DISABLE_ERRORS: false
FLAVOR_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true
