networks:
  edge:
    driver: bridge

  wan:
    driver: bridge

  apps:
    driver: bridge

  services:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: ${SERVICES_SUBNET}
          ip_range: ${SERVICES_DYNAMIC_IP_RANGE}

  media:
    driver: bridge
    ipam:
      config:
        - subnet: ${MEDIA_SUBNET}
          ip_range: ${MEDIA_DYNAMIC_IP_RANGE}

  observability:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: ${OBSERVABILITY_SUBNET}

include:
  - docker-compose-media-library.yml
  - docker-compose-nzb.yml
  - docker-compose-observability.yml
  - docker-compose-proxy.yml
  - docker-compose-servarr.yml
  - docker-compose-torrent.yml
  - docker-compose-vpn.yml
