name: torrent

x-healthcheck-defaults: &healthcheck-defaults
  interval: 60s
  retries: 5
  start_period: 30s
  timeout: 10s

x-limit-downloaders: &limit-downloaders
  deploy:
    resources:
      limits:
        memory: ${DOWNLOADERS_MEMORY}
        cpus: "${DOWNLOADERS_CPUS}"

services:
  qbittorrent:
    <<: *limit-downloaders
    image: docker.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    depends_on:
      ${VPN_PROVIDER}:
        condition: service_healthy
        restart: true
    profiles: ["${QBITTORRENT_PROFILE}"]
    network_mode: container:${VPN_PROVIDER}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: ["${CONFIG_FOLDER}/qbittorrent/.env"]
    environment:
      [
        "PGID=${QBITTORRENT_GID}",
        "PUID=${QBITTORRENT_UID}",
        "UMASK=${UMASK}",
        "TZ=${TIMEZONE}",
      ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CERTIFICATES_FOLDER}:/certs:ro
      - ${CONFIG_FOLDER}/qbittorrent/config:/config:z
      - ${TORRENTS_FOLDER}:/data/torrents:z
    healthcheck:
      <<: *healthcheck-defaults
      test: curl --fail --insecure https://${GLUETUN_SERVICES_IP}:${QBITTORRENT_HTTPS_PORT}/ || exit 1
  jdownloader2:
    <<: *limit-downloaders
    image: docker.io/jlesage/jdownloader-2:${JDOWNLOADER2_VERSION}
    container_name: jdownloader2
    depends_on:
      ${VPN_PROVIDER}:
        condition: service_healthy
        restart: true
    profiles: ["${JDOWNLOADER2_PROFILE}"]
    network_mode: container:${VPN_PROVIDER}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: ["${CONFIG_FOLDER}/jdownloader2/.env"]
    environment:
      ["USER_ID=${JDOWNLOADER2_UID}", "GROUP_ID=${JDOWNLOADER2_GID}", "TZ=${TIMEZONE}"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/jdownloader2/config:/config:z
      - ${DOWNLOADS_FOLDER}:/data/downloads:z
    healthcheck:
      <<: *healthcheck-defaults
      test: curl --fail --silent http://127.0.0.1:${JDOWNLOADER2_HTTP_PORT}/ || exit 1

  # deluge:
  #   image: docker.io/linuxserver/deluge:${DELUGE_VERSION}
  #   container_name: deluge
  #   depends_on: ["${VPN_PROVIDER}"]
  #   profiles: ["${DELUGE_PROFILE}"]
  #   network_mode: service:${VPN_PROVIDER}
  #   sysctls: ["net.ipv6.conf.all.disable_ipv6=1", net.ipv6.conf.default.disable_ipv6=1, net.ipv6.conf.lo.disable_ipv6=1]
  #   restart: unless-stopped
  #   env_file: ["${CONFIG_FOLDER}/deluge/.env"]
  #   environment:
  #     ["PGID=${GID}", "PUID=${UID}", "UMASK=${UMASK}", "TZ=${TIMEZONE}"]
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ${CERTIFICATES_FOLDER}:/certs:ro
  #     - ${CONFIG_FOLDER}/deluge/config:/config:z
  #     - ${TORRENTS_FOLDER}:/data/torrents:z
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1gb
  #         cpus: '0.5'
  #   memswap_limit: 1gb
