#!/usr/bin/env python3
"""Generate configs/homepage/config/services.yaml from services.yaml.template,
dropping any app whose compose profile is disabled in .env, and dropping any
section left empty as a result. Run on every `make start`, not just bootstrap,
so flipping a profile and restarting is enough to update Homepage; see the
comment at the top of services.yaml.template.
"""

import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print(
        "ERROR: PyYAML is required (pip install --user pyyaml or your distro's "
        "python3-yaml/python3-pyyaml package) to generate Homepage's services.yaml.",
        file=sys.stderr,
    )
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env"
TEMPLATE_FILE = REPO_ROOT / "configs/homepage/config/services.yaml.template"
OUTPUT_FILE = REPO_ROOT / "configs/homepage/config/services.yaml"

# Maps each entry's display name (the single key of its list item) to the
# .env *_PROFILE variable that gates it. Entries with no mapping here (there
# are none today) are always kept, since there's nothing to gate them on.
SERVICE_PROFILE = {
    "Sonarr": "SONARR_PROFILE",
    "Radarr": "RADARR_PROFILE",
    "Lidarr": "LIDARR_PROFILE",
    "Readarr": "READARR_PROFILE",
    "Mylar": "MYLAR_PROFILE",
    "Whisparr": "WHISPARR_PROFILE",
    "Bazarr": "BAZARR_PROFILE",
    "qBittorrent": "QBITTORRENT_PROFILE",
    "SABnzbd": "SABNZBD_PROFILE",
    "Prowlarr": "PROWLARR_PROFILE",
    "NZBHydra2": "NZBHYDRA2_PROFILE",
    "JDownloader2": "JDOWNLOADER2_PROFILE",
    "Jellyfin": "JELLYFIN_PROFILE",
    "Audiobookshelf": "AUDIOBOOKSHELF_PROFILE",
    "Calibre Web": "CALIBREWEB_PROFILE",
    "Calibre": "CALIBRE_PROFILE",
    "LazyLibrarian": "LAZYLIBRARIAN_PROFILE",
    "KOReader Sync": "KORSYNC_PROFILE",
    "Grafana": "GRAFANA_PROFILE",
    "Prometheus": "PROMETHEUS_PROFILE",
    "cAdvisor": "CADVISOR_PROFILE",
    # The Overview section's only entry embeds a Grafana dashboard, so it
    # rides on Grafana's own profile rather than having one of its own.
    "Metrics": "GRAFANA_PROFILE",
}


def read_profiles(env_file: Path) -> dict[str, bool]:
    profiles = {}
    for line in env_file.read_text().splitlines():
        m = re.match(r"^([A-Z0-9_]+_PROFILE)=(\S*)$", line)
        if m:
            profiles[m.group(1)] = m.group(2) == "enabled"
    return profiles


def is_enabled(name: str, profiles: dict[str, bool]) -> bool:
    var = SERVICE_PROFILE.get(name)
    if var is None:
        return True
    # Missing from .env entirely is not expected once bootstrapped, but
    # fails open (keeps the entry) rather than silently hiding an app over
    # a parsing mismatch.
    return profiles.get(var, True)


def main() -> int:
    if not ENV_FILE.is_file():
        print(f"{ENV_FILE} does not exist yet, skipping.", file=sys.stderr)
        return 0

    profiles = read_profiles(ENV_FILE)
    sections = yaml.safe_load(TEMPLATE_FILE.read_text())

    filtered_sections = []
    for section in sections:
        (section_name, entries), = section.items()
        filtered_entries = [
            entry
            for entry in entries
            if is_enabled(next(iter(entry)), profiles)
        ]
        if filtered_entries:
            filtered_sections.append({section_name: filtered_entries})

    with OUTPUT_FILE.open("w") as f:
        f.write(
            "# Generated by scripts/generate-homepage-services.py from\n"
            "# services.yaml.template on every `make start`. Edit the template,\n"
            "# not this file: it gets overwritten.\n"
        )
        yaml.dump(filtered_sections, f, default_flow_style=False, sort_keys=False)

    # Rootless Podman maps this host file to a different UID inside the
    # container (Homepage runs as HOMEPAGE_UID/HOMEPAGE_GID, neither of which
    # is the host user writing this file), so it needs to stay world-readable
    # or Homepage can't open its own config; matches write_secret_file()'s
    # same reasoning in scripts/rotate-api-keys.sh.
    OUTPUT_FILE.chmod(0o644)

    return 0


if __name__ == "__main__":
    sys.exit(main())
