---
name: MegaLinter

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: MegaLinter
        uses: oxsecurity/megalinter@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
